using Avalon.Common;
using Avalon.Items.Accessories.PreHardmode;
using Microsoft.Xna.Framework;
using Terraria;
using Terraria.ID;
using Terraria.ModLoader;


namespace Avalon.Items.Accessories.Hardmode
{
    public class MutatedStocking : ModItem // CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK CUM SOCK
    {
        public override void SetDefaults()
        {
            Item.rare = ItemRarityID.Pink;
            Item.Size = new Vector2(24);
            Item.accessory = true;
            Item.value = Item.sellPrice(0, 8);
        }
        public override void UpdateAccessory(Player player, bool hideVisual)
        {
            player.GetModPlayer<AvalonPlayer>().MutatedStocking = true;
        }
    }
}
